dj_learn/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('namecollect/', include('namecollect.urls')),
    path('admin/', admin.site.urls),
]

namecollect/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'namecollect'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.PersonCreate.as_view(), name = 'person_create'),
]

namecollect/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Class for Gender
class Gender(models.Model):
    gender = models.CharField(max_length=6)

    def __str__(self):
        return self.gender

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.PositiveIntegerField(validators=[MaxValueValidator(125, 'Age cannot be more than 125')], null=True)
    gender = models.ForeignKey('Gender', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.last_name
        

namecollect/views.py
from django.shortcuts import render, redirect 
from django.views import View
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.template.loader import render_to_string

from namecollect.models import Person


# Create your views here.

class MainView (View):
    def get(self, request):
        pl = Person.objects.all()

        ctx = {'person_list': pl}
        return render(request, 'namecollect/person_list.html', ctx)
        

class PersonCreate (CreateView):
    model=Person
    fields='__all__'
    success_url=reverse_lazy('namecollect:all')
    

namecollect/templates/namecollect/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Main</title>
</head>

<body>

    <div class="container">

        {% block content %}
        <h2>Person details</h2>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input class="btn btn-primary" type="submit" value="Submit">
            <input class="btn btn-primary" type="submit" onclick="window.location='{% url 'namecollect:all' %}'; return false;" value="Cancel">
        </form>

        {% endblock %}

    </div>
</body> 
</html> 



    

namecollect/templates/namecollect/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Main</title>
</head>

<body>

<div class="container">
{% block content %}
    <h1>Akira Person list</h1>
    {% if person_list %}
    <ul>
        {% for person in person_list %}
            <li>
                    {{person.first_name}} {{person.last_name}}, Age: {{person.age}}, {{person.gender}}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no names in this database</p>
    {% endif %}
    <p>
        <a class="btn btn-primary" href="{% url 'namecollect:person_create' %}" >add a person</a>
    </p>
{% endblock %}
</div>
</body>

</html>


    